# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
# 
# Translators:
# abc Def <hdogan1974@gmail.com>, 2020
# Emir SARI, 2024
# Demiray Muhterem <mdemiray@msn.com>, 2024
# 
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2024-11-29 13:55+0100\n"
"PO-Revision-Date: 2017-08-09 10:34+0000\n"
"Last-Translator: Demiray Muhterem <mdemiray@msn.com>, 2024\n"
"Language-Team: Turkish (Turkey) (https://app.transifex.com/calamares/teams/20061/tr_TR/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: tr_TR\n"
"Plural-Forms: nplurals=2; plural=(n > 1);\n"

#: src/modules/bootloader/main.py:46
msgid "Install bootloader."
msgstr "Önyükleyici kuruluyor."

#: src/modules/bootloader/main.py:671
msgid "Failed to install grub, no partitions defined in global storage"
msgstr "Grub kurulamadı, global depolamada tanımlı bölüm yok"

#: src/modules/bootloader/main.py:931
msgid "Bootloader installation error"
msgstr "Önyükleyici kurulum hatası"

#: src/modules/bootloader/main.py:932
msgid ""
"The bootloader could not be installed. The installation command "
"<pre>{!s}</pre> returned error code {!s}."
msgstr ""
"Önyükleyici kurulamadı. Kurulum komutu <pre>{!s}</pre>, {!s} hata kodunu "
"döndürdü."

#: src/modules/displaymanager/main.py:525
msgid "Cannot write LXDM configuration file"
msgstr "LXDM yapılandırma dosyası yazılamıyor"

#: src/modules/displaymanager/main.py:526
msgid "LXDM config file {!s} does not exist"
msgstr "LXDM yapılandırma dosyası {!s} yok"

#: src/modules/displaymanager/main.py:614
msgid "Cannot write LightDM configuration file"
msgstr "LightDM yapılandırma dosyası yazılamıyor"

#: src/modules/displaymanager/main.py:615
msgid "LightDM config file {!s} does not exist"
msgstr "LightDM yapılandırma dosyası {!s} yok"

#: src/modules/displaymanager/main.py:700
msgid "Cannot configure LightDM"
msgstr "LightDM yapılandırılamıyor"

#: src/modules/displaymanager/main.py:701
msgid "No LightDM greeter installed."
msgstr "Kurulu LightDM karşılayıcısı yok."

#: src/modules/displaymanager/main.py:732
msgid "Cannot write SLIM configuration file"
msgstr "SLIM yapılandırma dosyası yazılamıyor"

#: src/modules/displaymanager/main.py:733
msgid "SLIM config file {!s} does not exist"
msgstr "SLIM yapılandırma dosyası {!s} yok"

#: src/modules/displaymanager/main.py:956
msgid "No display managers selected for the displaymanager module."
msgstr "displaymanager modülü için seçili görüntü yöneticisi yok"

#: src/modules/displaymanager/main.py:957
msgid ""
"The displaymanagers list is empty or undefined in both globalstorage and "
"displaymanager.conf."
msgstr ""
"displaymanagers listesi hem globalstorage hem de displaymanager.conf'ta boş "
"veya tanımsız."

#: src/modules/displaymanager/main.py:1044
msgid "Display manager configuration was incomplete"
msgstr "Görüntü yöneticisi yapılandırma işi tamamlanamadı"

#: src/modules/dracut/main.py:29
msgid "Creating initramfs with dracut."
msgstr "Dracut ile initramfs oluşturuluyor."

#: src/modules/dracut/main.py:63
msgid "Failed to run dracut"
msgstr "Dracut çalıştırılamadı"

#: src/modules/dracut/main.py:64
#, python-brace-format
msgid "Dracut failed to run on the target with return code: {return_code}"
msgstr "Dracut, dönüş koduyla hedefte çalıştırılamadı: {return_code}"

#: src/modules/dummypython/main.py:35
msgid "Dummy python job."
msgstr "Dummy python job."

#: src/modules/dummypython/main.py:37 src/modules/dummypython/main.py:104
#: src/modules/dummypython/main.py:105
msgid "Dummy python step {}"
msgstr "Dummy python step {}"

#: src/modules/fstab/main.py:29
msgid "Writing fstab."
msgstr "Fstab dosyasına yazılıyor."

#: src/modules/fstab/main.py:382 src/modules/fstab/main.py:388
#: src/modules/fstab/main.py:416 src/modules/initcpiocfg/main.py:267
#: src/modules/initcpiocfg/main.py:271 src/modules/initramfscfg/main.py:85
#: src/modules/initramfscfg/main.py:89 src/modules/localecfg/main.py:140
#: src/modules/mount/main.py:344 src/modules/networkcfg/main.py:106
#: src/modules/openrcdmcryptcfg/main.py:72
#: src/modules/openrcdmcryptcfg/main.py:76 src/modules/rawfs/main.py:165
msgid "Configuration Error"
msgstr "Yapılandırma Hatası"

#: src/modules/fstab/main.py:383 src/modules/initramfscfg/main.py:86
#: src/modules/mount/main.py:345 src/modules/openrcdmcryptcfg/main.py:73
#: src/modules/rawfs/main.py:166
msgid "No partitions are defined for <pre>{!s}</pre> to use."
msgstr "<pre>{!s}</pre> kullanması için hiçbir bölüm tanımlanmadı."

#: src/modules/fstab/main.py:389 src/modules/initramfscfg/main.py:90
#: src/modules/localecfg/main.py:141 src/modules/networkcfg/main.py:107
#: src/modules/openrcdmcryptcfg/main.py:77
msgid "No root mount point is given for <pre>{!s}</pre> to use."
msgstr "<pre>{!s}</pre> kullanması için kök bağlama noktası verilmedi."

#: src/modules/fstab/main.py:417
msgid "No <pre>{!s}</pre> configuration is given for <pre>{!s}</pre> to use."
msgstr ""
"<pre>{!s}</pre>'nin kullanması için <pre>{!s}</pre> yapılandırması "
"verilmemiştir."

#: src/modules/grubcfg/main.py:30
msgid "Configure GRUB."
msgstr "GRUB'u yapılandırın."

#: src/modules/hwclock/main.py:26
msgid "Setting hardware clock."
msgstr "Donanım saati ayarlanıyor."

#: src/modules/initcpiocfg/main.py:27
msgid "Configuring mkinitcpio."
msgstr "Mkinitcpio yapılandırılıyor."

#: src/modules/initcpiocfg/main.py:268
msgid "No partitions are defined for <pre>initcpiocfg</pre>."
msgstr "<pre>initcpiocfg</pre> için herhangi bir bölüm tanımlanmadı."

#: src/modules/initcpiocfg/main.py:272
msgid "No root mount point for <pre>initcpiocfg</pre>."
msgstr "<pre>initcpiocfg</pre> için kök bağlama noktası yok."

#: src/modules/initramfscfg/main.py:32
msgid "Configuring initramfs."
msgstr "Initramfs yapılandırılıyor."

#: src/modules/localecfg/main.py:31
msgid "Configuring locales."
msgstr "Sistem yerelleri yapılandırılıyor."

#: src/modules/mkinitfs/main.py:27
msgid "Creating initramfs with mkinitfs."
msgstr "Mkinitfs ile initramfs oluşturuluyor."

#: src/modules/mkinitfs/main.py:49
msgid "Failed to run mkinitfs on the target"
msgstr "Hedefte mkinitfs çalıştırılamadı"

#: src/modules/mkinitfs/main.py:50
msgid "The exit code was {}"
msgstr "Çıkış kodu {} idi"

#: src/modules/mount/main.py:43
msgid "Mounting partitions."
msgstr "Bölümler bağlanıyor."

#: src/modules/mount/main.py:171 src/modules/mount/main.py:207
msgid "Internal error mounting zfs datasets"
msgstr "Dahili bağlama hatası zfs veri kümeleri"

#: src/modules/mount/main.py:183
msgid "Failed to import zpool"
msgstr "zpool içe aktarılamadı"

#: src/modules/mount/main.py:199
msgid "Failed to unlock zpool"
msgstr "zpool kilidi açılamadı"

#: src/modules/mount/main.py:216 src/modules/mount/main.py:221
msgid "Failed to set zfs mountpoint"
msgstr "zfs bağlama noktası ayarlanamadı"

#: src/modules/mount/main.py:386
msgid "zfs mounting error"
msgstr "zfs bağlama hatası"

#: src/modules/networkcfg/main.py:30
msgid "Saving network configuration."
msgstr "Ağ yapılandırma kaydediliyor."

#: src/modules/openrcdmcryptcfg/main.py:26
msgid "Configuring OpenRC dmcrypt service."
msgstr "OpenRC dmcrypt hizmeti yapılandırılıyor."

#: src/modules/packages/main.py:54 src/modules/packages/main.py:65
#: src/modules/packages/main.py:75
msgid "Install packages."
msgstr "Paketleri kur."

#: src/modules/packages/main.py:63
#, python-format
msgid "Processing packages (%(count)d / %(total)d)"
msgstr "Paketler işleniyor (%(count)d / %(total)d)"

#: src/modules/packages/main.py:68
#, python-format
msgid "Installing one package."
msgid_plural "Installing %(num)d packages."
msgstr[0] "1 paket kuruluyor"
msgstr[1] "%(num)d paket kuruluyor."

#: src/modules/packages/main.py:71
#, python-format
msgid "Removing one package."
msgid_plural "Removing %(num)d packages."
msgstr[0] "1 paket kaldırılıyor."
msgstr[1] "%(num)d paket kaldırılıyor."

#: src/modules/packages/main.py:775 src/modules/packages/main.py:787
#: src/modules/packages/main.py:815
msgid "Package Manager error"
msgstr "Paket Yöneticisi hatası"

#: src/modules/packages/main.py:776
msgid ""
"The package manager could not prepare updates. The command <pre>{!s}</pre> "
"returned error code {!s}."
msgstr ""
"Paket yöneticisi güncellemeleri hazırlayamadı. <pre>{!s}</pre> komutu {!s} "
"hata kodunu döndürdü."

#: src/modules/packages/main.py:788
msgid ""
"The package manager could not update the system. The command <pre>{!s}</pre>"
" returned error code {!s}."
msgstr ""
"Paket yöneticisi sistemi güncelleyemedi. <pre>{!s}</pre> komutu {!s} hata "
"kodunu döndürdü."

#: src/modules/packages/main.py:816
msgid ""
"The package manager could not make changes to the installed system. The "
"command <pre>{!s}</pre> returned error code {!s}."
msgstr ""
"Paket yöneticisi kurulu sistemde değişiklik yapamadı. <pre>{!s}</pre> komutu"
" {!s} hata kodunu döndürdü."

#: src/modules/plymouthcfg/main.py:27
msgid "Configure Plymouth theme"
msgstr "Plymouth temasını yapılandır"

#: src/modules/rawfs/main.py:26
msgid "Installing data."
msgstr "Veri kuruluyor."

#: src/modules/services-openrc/main.py:29
msgid "Configure OpenRC services"
msgstr " OpenRC hizmetlerini yapılandır"

#: src/modules/services-openrc/main.py:57
msgid "Cannot add service {name!s} to run-level {level!s}."
msgstr "{name!s} hizmeti, {level!s} çalışma düzeyine ekleyemiyor."

#: src/modules/services-openrc/main.py:59
msgid "Cannot remove service {name!s} from run-level {level!s}."
msgstr "{name!s} hizmeti {level!s} çalışma düzeyinden kaldırılamıyor."

#: src/modules/services-openrc/main.py:61
msgid ""
"Unknown service-action <code>{arg!s}</code> for service {name!s} in run-"
"level {level!s}."
msgstr ""
"Çalışma düzeyinde {level!s} hizmetinde {name!s} servisi için bilinmeyen "
"hizmet eylemi <code>{arg!s}</code>."

#: src/modules/services-openrc/main.py:93
msgid "Cannot modify service"
msgstr "Hizmet değiştirilemiyor"

#: src/modules/services-openrc/main.py:94
msgid ""
"<code>rc-update {arg!s}</code> call in chroot returned error code {num!s}."
msgstr ""
" <code>rc-update {arg!s}</code> çağrısında chroot {num!s} hata kodunu "
"döndürdü."

#: src/modules/services-openrc/main.py:101
msgid "Target runlevel does not exist"
msgstr "Hedef çalıştırma düzeyi yok"

#: src/modules/services-openrc/main.py:102
msgid ""
"The path for runlevel {level!s} is <code>{path!s}</code>, which does not "
"exist."
msgstr "{level!s} çalıştırma düzeyi yolu, var olmayan <code>{path!s}</code>."

#: src/modules/services-openrc/main.py:110
msgid "Target service does not exist"
msgstr "Hedef hizmet yok"

#: src/modules/services-openrc/main.py:111
msgid ""
"The path for service {name!s} is <code>{path!s}</code>, which does not "
"exist."
msgstr "{name!s} hizmeti yolu, var olmayan <code>{path!s}</code>."

#: src/modules/services-systemd/main.py:26
msgid "Configure systemd units"
msgstr "Systemd birimlerini yapılandır"

#: src/modules/services-systemd/main.py:64
msgid "Cannot modify unit"
msgstr "Birim değiştirilemiyor"

#: src/modules/services-systemd/main.py:65
msgid ""
"<code>systemctl {_action!s}</code> call in chroot returned error code "
"{_exit_code!s}."
msgstr ""
"chroot üzerinde <code>systemctl {_action!s}</code> çağrısı, {_exit_code!s} "
"hata kodunu döndürdü."

#: src/modules/services-systemd/main.py:66
msgid "Cannot {_action!s} systemd unit <code>{_name!s}</code>."
msgstr "{_action!s} sistem birimi <code>{_name!s}</code> yapılamıyor."

#: src/modules/unpackfs/main.py:34
msgid "Filling up filesystems."
msgstr "Dosya sistemi genişletiliyor."

#: src/modules/unpackfs/main.py:255
msgid "rsync failed with error code {}."
msgstr "rsync {} hata koduyla başarısız oldu."

#: src/modules/unpackfs/main.py:300
msgid "Unpacking image {}/{}, file {}/{}"
msgstr "Açılan kurulum medyası {}/{}, dışa aktarılan dosya sayısı {}/{}"

#: src/modules/unpackfs/main.py:315
msgid "Starting to unpack {}"
msgstr "{} paketi açılıyor"

#: src/modules/unpackfs/main.py:324 src/modules/unpackfs/main.py:480
msgid "Failed to unpack image \"{}\""
msgstr "\"{}\" kurulum medyası aktarılamadı"

#: src/modules/unpackfs/main.py:443
msgid "No mount point for root partition"
msgstr "kök bölüm için bağlama noktası yok"

#: src/modules/unpackfs/main.py:444
msgid "globalstorage does not contain a \"rootMountPoint\" key."
msgstr "globalstorage bir \"rootMountPoint\" anahtarı içermiyor."

#: src/modules/unpackfs/main.py:447
msgid "Bad mount point for root partition"
msgstr "Kök bölüm için hatalı bağlama noktası"

#: src/modules/unpackfs/main.py:448
msgid "rootMountPoint is \"{}\", which does not exist."
msgstr "rootMountPoint, var olmayan \"{}\"."

#: src/modules/unpackfs/main.py:452 src/modules/unpackfs/main.py:468
#: src/modules/unpackfs/main.py:472 src/modules/unpackfs/main.py:478
#: src/modules/unpackfs/main.py:515
msgid "Bad unpackfs configuration"
msgstr "Hatalı unpackfs yapılandırması"

#: src/modules/unpackfs/main.py:453
msgid "There is no configuration information."
msgstr "Yapılandırma bilgisi yok."

#: src/modules/unpackfs/main.py:469
msgid "The filesystem for \"{}\" ({}) is not supported by your current kernel"
msgstr "\"{}\" ({}) dosya sistemi, şu anki çekirdeğiniz tarafından desteklenmiyor"

#: src/modules/unpackfs/main.py:473
msgid "The source filesystem \"{}\" does not exist"
msgstr "\"{}\" kaynak dosya sistemi yok"

#: src/modules/unpackfs/main.py:479
msgid ""
"Failed to find unsquashfs, make sure you have the squashfs-tools package "
"installed."
msgstr ""
"Unsquashfs bulunamadı, squashfs-tools paketinin kurulu olduğundan emin olun."

#: src/modules/unpackfs/main.py:516
msgid "The destination \"{}\" in the target system is not a directory"
msgstr "Hedef sistemdeki \"{}\" hedefi bir dizin değil"

#: src/modules/zfshostid/main.py:27
msgid "Copying zfs generated hostid."
msgstr "Oluşturulan hostid zfs kopyalanıyor."
