# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
# 
# Translators:
# Xəyyam Qocayev <xxmn77@gmail.com>, 2023
# 
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2024-11-29 13:55+0100\n"
"PO-Revision-Date: 2017-08-09 10:34+0000\n"
"Last-Translator: Xəyyam Qocayev <xxmn77@gmail.com>, 2023\n"
"Language-Team: Azerbaijani (https://app.transifex.com/calamares/teams/20061/az/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: az\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: src/modules/bootloader/main.py:46
msgid "Install bootloader."
msgstr "Önyükləyici qurulur."

#: src/modules/bootloader/main.py:671
msgid "Failed to install grub, no partitions defined in global storage"
msgstr "Grub quraşdırılmadı, ümumi yaddaş üçün bölmələr təyin olunmayıb"

#: src/modules/bootloader/main.py:931
msgid "Bootloader installation error"
msgstr "Önyükləyicinin quraşdırılmasında xəta"

#: src/modules/bootloader/main.py:932
msgid ""
"The bootloader could not be installed. The installation command "
"<pre>{!s}</pre> returned error code {!s}."
msgstr ""
"Önyükləyici quraşdırıla bilmədi. Quraşdırma əmri <pre>{!s}</pre>, xəta kodu "
"{!s} ilə cavab verdi."

#: src/modules/displaymanager/main.py:525
msgid "Cannot write LXDM configuration file"
msgstr "LXDM tənzimləmə faylı yazıla bilmir"

#: src/modules/displaymanager/main.py:526
msgid "LXDM config file {!s} does not exist"
msgstr "LXDM tənzimləmə faylı {!s} mövcud deyil"

#: src/modules/displaymanager/main.py:614
msgid "Cannot write LightDM configuration file"
msgstr "LightDM tənzimləmə faylı yazıla bilmir"

#: src/modules/displaymanager/main.py:615
msgid "LightDM config file {!s} does not exist"
msgstr "LightDM tənzimləmə faylı {!s} mövcud deyil"

#: src/modules/displaymanager/main.py:700
msgid "Cannot configure LightDM"
msgstr "LightDM tənzimlənə bilmir"

#: src/modules/displaymanager/main.py:701
msgid "No LightDM greeter installed."
msgstr "LightDM qarşılama quraşdırılmayıb."

#: src/modules/displaymanager/main.py:732
msgid "Cannot write SLIM configuration file"
msgstr "SLİM tənzimləmə faylı yazıla bilmir"

#: src/modules/displaymanager/main.py:733
msgid "SLIM config file {!s} does not exist"
msgstr "SLİM tənzimləmə faylı {!s} mövcud deyil"

#: src/modules/displaymanager/main.py:956
msgid "No display managers selected for the displaymanager module."
msgstr "displaymanager modulu üçün ekran menecerləri seçilməyib."

#: src/modules/displaymanager/main.py:957
msgid ""
"The displaymanagers list is empty or undefined in both globalstorage and "
"displaymanager.conf."
msgstr ""
"Ekran menecerləri siyahısı həm qlobal yaddaşda, həm də displaymanager.conf-"
"da boşdur və ya təyin olunmamışdır."

#: src/modules/displaymanager/main.py:1044
msgid "Display manager configuration was incomplete"
msgstr "Ekran meneceri tənzimləmələri başa çatmadı"

#: src/modules/dracut/main.py:29
msgid "Creating initramfs with dracut."
msgstr "Dracut ilə initramfs yaratmaq."

#: src/modules/dracut/main.py:63
msgid "Failed to run dracut"
msgstr "Dracut-u işə salmaq mümkün olmadı"

#: src/modules/dracut/main.py:64
#, python-brace-format
msgid "Dracut failed to run on the target with return code: {return_code}"
msgstr ""
"Dracut-u hədəfdə işə salmaq mümkün olmadı və bu kod ilə cavab verdi: "
"{return_code}"

#: src/modules/dummypython/main.py:35
msgid "Dummy python job."
msgstr "Dummy python işi."

#: src/modules/dummypython/main.py:37 src/modules/dummypython/main.py:104
#: src/modules/dummypython/main.py:105
msgid "Dummy python step {}"
msgstr "{} Dummy python addımı"

#: src/modules/fstab/main.py:29
msgid "Writing fstab."
msgstr "fstab yazılır."

#: src/modules/fstab/main.py:382 src/modules/fstab/main.py:388
#: src/modules/fstab/main.py:416 src/modules/initcpiocfg/main.py:267
#: src/modules/initcpiocfg/main.py:271 src/modules/initramfscfg/main.py:85
#: src/modules/initramfscfg/main.py:89 src/modules/localecfg/main.py:140
#: src/modules/mount/main.py:344 src/modules/networkcfg/main.py:106
#: src/modules/openrcdmcryptcfg/main.py:72
#: src/modules/openrcdmcryptcfg/main.py:76 src/modules/rawfs/main.py:165
msgid "Configuration Error"
msgstr "Tənzimləmə xətası"

#: src/modules/fstab/main.py:383 src/modules/initramfscfg/main.py:86
#: src/modules/mount/main.py:345 src/modules/openrcdmcryptcfg/main.py:73
#: src/modules/rawfs/main.py:166
msgid "No partitions are defined for <pre>{!s}</pre> to use."
msgstr "<pre>{!s}</pre> istifadə etmək üçün bölmələr təyin edilməyib"

#: src/modules/fstab/main.py:389 src/modules/initramfscfg/main.py:90
#: src/modules/localecfg/main.py:141 src/modules/networkcfg/main.py:107
#: src/modules/openrcdmcryptcfg/main.py:77
msgid "No root mount point is given for <pre>{!s}</pre> to use."
msgstr ""
"<pre>{!s}</pre> istifadə etmək üçün kök qoşulma nöqtəsi təyin edilməyib."

#: src/modules/fstab/main.py:417
msgid "No <pre>{!s}</pre> configuration is given for <pre>{!s}</pre> to use."
msgstr ""
"İstifadə etmək üçün, <pre>{!s}</pre> tənzimləməsi, <pre>{!s}</pre> üçün "
"göstərilməyib."

#: src/modules/grubcfg/main.py:30
msgid "Configure GRUB."
msgstr "GRUB tənzimləmələri"

#: src/modules/hwclock/main.py:26
msgid "Setting hardware clock."
msgstr "Aparat saatını ayarlamaq."

#: src/modules/initcpiocfg/main.py:27
msgid "Configuring mkinitcpio."
msgstr "mkinitcpio tənzimlənir."

#: src/modules/initcpiocfg/main.py:268
msgid "No partitions are defined for <pre>initcpiocfg</pre>."
msgstr "<pre>initcpiocfg</pre> üçün bölmə müəyyən edilən bölmə yoxdur."

#: src/modules/initcpiocfg/main.py:272
msgid "No root mount point for <pre>initcpiocfg</pre>."
msgstr "<pre>initcpiocfg</pre> üçün kök (root) qoşulma nöqtəsi yoxdur."

#: src/modules/initramfscfg/main.py:32
msgid "Configuring initramfs."
msgstr "initramfs tənzimlənir."

#: src/modules/localecfg/main.py:31
msgid "Configuring locales."
msgstr "Lokallaşma tənzimlənir."

#: src/modules/mkinitfs/main.py:27
msgid "Creating initramfs with mkinitfs."
msgstr "mkinitfs ilə initramfs yaradılır"

#: src/modules/mkinitfs/main.py:49
msgid "Failed to run mkinitfs on the target"
msgstr "Hədəfdə mkinitfs başlatmaq baş tutmadı"

#: src/modules/mkinitfs/main.py:50
msgid "The exit code was {}"
msgstr "Çıxış kodu {} idi"

#: src/modules/mount/main.py:43
msgid "Mounting partitions."
msgstr "Disk bölmələri qoşulur."

#: src/modules/mount/main.py:171 src/modules/mount/main.py:207
msgid "Internal error mounting zfs datasets"
msgstr "Zfs verilənlər dəstinin qoşulmasında daxil xəta"

#: src/modules/mount/main.py:183
msgid "Failed to import zpool"
msgstr "Zpool idxalı baş tutmadı"

#: src/modules/mount/main.py:199
msgid "Failed to unlock zpool"
msgstr "Zpool kiliddən çıxarıla bilmədi"

#: src/modules/mount/main.py:216 src/modules/mount/main.py:221
msgid "Failed to set zfs mountpoint"
msgstr "Zfs qoşulma nöqtəsi təyin olunmadı"

#: src/modules/mount/main.py:386
msgid "zfs mounting error"
msgstr "zfs qoşulmasında xəta"

#: src/modules/networkcfg/main.py:30
msgid "Saving network configuration."
msgstr "Şəbəkə ayarları saxlanılır."

#: src/modules/openrcdmcryptcfg/main.py:26
msgid "Configuring OpenRC dmcrypt service."
msgstr "OpenRC dmcrypt xidməti tənzimlənir."

#: src/modules/packages/main.py:54 src/modules/packages/main.py:65
#: src/modules/packages/main.py:75
msgid "Install packages."
msgstr "Paketləri quraşdırmaq."

#: src/modules/packages/main.py:63
#, python-format
msgid "Processing packages (%(count)d / %(total)d)"
msgstr "(%(count)d / %(total)d) paketləri işlənir"

#: src/modules/packages/main.py:68
#, python-format
msgid "Installing one package."
msgid_plural "Installing %(num)d packages."
msgstr[0] "Bir paket quraşdırılır."
msgstr[1] "%(num)d paket quraşdırılır."

#: src/modules/packages/main.py:71
#, python-format
msgid "Removing one package."
msgid_plural "Removing %(num)d packages."
msgstr[0] "Bir paket silinir"
msgstr[1] "%(num)d paket silinir."

#: src/modules/packages/main.py:775 src/modules/packages/main.py:787
#: src/modules/packages/main.py:815
msgid "Package Manager error"
msgstr "Paket meneceri xətası"

#: src/modules/packages/main.py:776
msgid ""
"The package manager could not prepare updates. The command <pre>{!s}</pre> "
"returned error code {!s}."
msgstr ""
"Bu paket meneceri yenilənmələri hazırlaya bilmədi. <pre>{!s}</pre> əmri xəta"
" kodu {!s} ilə cavab verdi."

#: src/modules/packages/main.py:788
msgid ""
"The package manager could not update the system. The command <pre>{!s}</pre>"
" returned error code {!s}."
msgstr ""
"Paket meneceri sistemi yeniləyə bimədi. <pre>{!s}</pre> əmri xəta kodu {!s} "
"ilə cavab verdi."

#: src/modules/packages/main.py:816
msgid ""
"The package manager could not make changes to the installed system. The "
"command <pre>{!s}</pre> returned error code {!s}."
msgstr ""
"Paket meneceri dəyişiklikləri sistemə tətbiq edə bilmədi. <pre>{!s}</pre> "
"əmri xəta kodu {!s} ilə cavab verdi."

#: src/modules/plymouthcfg/main.py:27
msgid "Configure Plymouth theme"
msgstr "Plymouth mövzusu tənzimlənməsi"

#: src/modules/rawfs/main.py:26
msgid "Installing data."
msgstr "Quraşdırılma tarixi."

#: src/modules/services-openrc/main.py:29
msgid "Configure OpenRC services"
msgstr "OpenRC xidmətlərini tənzimləmək"

#: src/modules/services-openrc/main.py:57
msgid "Cannot add service {name!s} to run-level {level!s}."
msgstr "{name!s} xidməti {level!s} işləmə səviyyəsinə əlavə edilə bilmir."

#: src/modules/services-openrc/main.py:59
msgid "Cannot remove service {name!s} from run-level {level!s}."
msgstr "{name!s} xidməti {level!s} iş səviyyəsindən silinə bilmir."

#: src/modules/services-openrc/main.py:61
msgid ""
"Unknown service-action <code>{arg!s}</code> for service {name!s} in run-"
"level {level!s}."
msgstr ""
"{level!s} işləmə səviyyəsindəki {name!s} xidməti üçün naməlum "
"<code>{arg!s}</code> xidmət fəaliyyəti."

#: src/modules/services-openrc/main.py:93
msgid "Cannot modify service"
msgstr "Xidmətdə dəyişiklik etmək mümkün olmadı"

#: src/modules/services-openrc/main.py:94
msgid ""
"<code>rc-update {arg!s}</code> call in chroot returned error code {num!s}."
msgstr ""
"<code>rc-update {arg!s}</code> chroot-da çağırışına {num!s} xəta kodu ilə "
"cavab verildi."

#: src/modules/services-openrc/main.py:101
msgid "Target runlevel does not exist"
msgstr "Hədəf işləmə səviyyəsi mövcud deyil"

#: src/modules/services-openrc/main.py:102
msgid ""
"The path for runlevel {level!s} is <code>{path!s}</code>, which does not "
"exist."
msgstr ""
"{level!s} işləmə səviyyəsi üçün <code>{path!s}</code> yolu mövcud deyil."

#: src/modules/services-openrc/main.py:110
msgid "Target service does not exist"
msgstr "Hədəf xidməti mövcud deyil"

#: src/modules/services-openrc/main.py:111
msgid ""
"The path for service {name!s} is <code>{path!s}</code>, which does not "
"exist."
msgstr "{name!s} üçün <code>{path!s}</code> yolu mövcud deyil."

#: src/modules/services-systemd/main.py:26
msgid "Configure systemd units"
msgstr "systemd modullarını tənzimləyin"

#: src/modules/services-systemd/main.py:64
msgid "Cannot modify unit"
msgstr "Modulda dəyişiklik etmək mümkün olmadı"

#: src/modules/services-systemd/main.py:65
msgid ""
"<code>systemctl {_action!s}</code> call in chroot returned error code "
"{_exit_code!s}."
msgstr ""
"Chroot mühitində </code>systemctl {_action!s}</code> çağırışı {_exit_code!s}"
" kodu ilə cavab verdi."

#: src/modules/services-systemd/main.py:66
msgid "Cannot {_action!s} systemd unit <code>{_name!s}</code>."
msgstr "<code>{_name!s}</code> systemd modulunu {_action!s} mümkün olmadı."

#: src/modules/unpackfs/main.py:34
msgid "Filling up filesystems."
msgstr "Fayl sistemlərini doldurmaq."

#: src/modules/unpackfs/main.py:255
msgid "rsync failed with error code {}."
msgstr "rsync uğursuz oldu, xəta kodu: {}."

#: src/modules/unpackfs/main.py:300
msgid "Unpacking image {}/{}, file {}/{}"
msgstr ""
"{}/{} quraşdırma faylı paketdən çıxarılır, çıxarılan faylların sayı {}/{}"

#: src/modules/unpackfs/main.py:315
msgid "Starting to unpack {}"
msgstr "Quraşdırma faylı paketdən çıxarılır {}"

#: src/modules/unpackfs/main.py:324 src/modules/unpackfs/main.py:480
msgid "Failed to unpack image \"{}\""
msgstr "\"{}\" quraşdırma faylının tərkibini çıxarmaq alınmadı"

#: src/modules/unpackfs/main.py:443
msgid "No mount point for root partition"
msgstr "Kök bölməsi üçün qoşulma nöqtəsi yoxdur"

#: src/modules/unpackfs/main.py:444
msgid "globalstorage does not contain a \"rootMountPoint\" key."
msgstr "globalstorage tərkibində bir \"rootMountPoint\" açarı yoxdur."

#: src/modules/unpackfs/main.py:447
msgid "Bad mount point for root partition"
msgstr "Kök bölməsi üçün xətalı qoşulma nöqtəsi"

#: src/modules/unpackfs/main.py:448
msgid "rootMountPoint is \"{}\", which does not exist."
msgstr "rootMountPoint \"{}\" mövcud deyil."

#: src/modules/unpackfs/main.py:452 src/modules/unpackfs/main.py:468
#: src/modules/unpackfs/main.py:472 src/modules/unpackfs/main.py:478
#: src/modules/unpackfs/main.py:515
msgid "Bad unpackfs configuration"
msgstr "Xətalı unpackfs tənzimləməsi"

#: src/modules/unpackfs/main.py:453
msgid "There is no configuration information."
msgstr "Tənzimləmə məlumatı yoxdur"

#: src/modules/unpackfs/main.py:469
msgid "The filesystem for \"{}\" ({}) is not supported by your current kernel"
msgstr "\"{}\" ({}) fayl sistemi sizin nüvəniz tərəfindən dəstəklənmir"

#: src/modules/unpackfs/main.py:473
msgid "The source filesystem \"{}\" does not exist"
msgstr "\"{}\" mənbə fayl sistemi mövcud deyil"

#: src/modules/unpackfs/main.py:479
msgid ""
"Failed to find unsquashfs, make sure you have the squashfs-tools package "
"installed."
msgstr ""
"Unsquashfs tapılmadı, squashfs-tools paketinin quraşdırıldığına əmin olun."

#: src/modules/unpackfs/main.py:516
msgid "The destination \"{}\" in the target system is not a directory"
msgstr "Hədəf sistemində təyin edilən \"{}\", qovluq deyil"

#: src/modules/zfshostid/main.py:27
msgid "Copying zfs generated hostid."
msgstr "Yaradılan zfs host İD-si kopyalanır."
